### ISSUE TITLE
VPC > VPC Management

### ISSUE THREAD

**Issue by YuSungDuk** [NaverCloudPlatform/terraform-provider-ncloud-tmp#4]
- getVpcList
- getVpcDetail
- createVpc
- deleteVpc

**Comment by sangkyu-kim** [comment]
### Schema

Schema | Required | Optional | Computed | ForceNew | Validate
-- | -- | -- | -- | -- | --
vpc_no | Y |   | Y |   |  
name | Y |   |   |   | Y
ipv4_cidr_block | Y |   |   | Y | Y
status |   |   | Y |   |
